[general]
live_config_reload = true
working_directory = '/Users/amuszynski/Documents/Whisker/'

[window]
decorations = "Buttonless"
opacity = 0.90
padding = { x = 8, y = 8 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 22

[env]
term = "alacritty-direct"
